# Welcome to Jekyll!

# Website settings
title: ARN
description: Rumeysa's blog.
keywords: 'ARN,arncelik,blog,github'
baseurl: ''  # if you have suburl as homepage like '/homepage', please change it to '/homepage'
#url: 'http://www.jack003.com'
# url: "http://127.0.0.1:4000"
img_path: '/static/assets/img/blog'

# author
author:
  name: 'ARN'
  first_name: 'Rumeysa'
  last_name: 'Celik'
  #cv: 'http://cv.jack003.com'
  email: 'arncelik@gmail.com'
  #facebook_username: 'arncelik'
  github_username: 'arncelik'
  avatar: '/static/assets/img/landing/ARN.jpg'
  desc: 'Undergraduate student at North American University,Bioinformatics/Computaional Biology Enthusiast.'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: ARN
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d0
# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
